dist: focal
language: python
env:
    global:
        - PGVER=12
        - PGPORT=5432
addons:
  postgresql: "12"
  apt:
    packages:
    - postgresql-12
    - postgresql-client-12
# services:
#   - postgresql
#   - docker
python:
  - "3.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libsqlite3-dev
 - sqlite3 --version
 - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
before_script:
  - psql -c 'create database travis_ci_test_repo_tools;' -U postgres
install:
  - pip install codecov pytest-cov
  - pip install psycopg2
  - pip install -r requirements.txt
  - python setup.py develop
script: pytest --cov=./
after_success:
  - codecov
