dist: bionic
language: python
services:
  - postgresql
#   - docker
python:
  - "3.7"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -y libsqlite3-dev
 - sqlite3 --version
before_script:
  - psql -c 'create database travis_ci_test_repo_tools;' -U postgres
install:
  - pip install codecov pytest-cov
  - pip install psycopg2
  - pip install -r requirements.txt
  - python setup.py develop
script: pytest --cov=./
after_success:
  - codecov
